name: SecurityVision
favicon: null
layout_spectrum: 0.99549
typography_spectrum: 0.00468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6704099816270173
  lightness: 0.49958516913466156
  saturation: 0.21167214587330818
  rhythmicContrast: 0.8685266559477895
purpose: []
